name: Clang-Tidy-on-PR

on:
  pull_request:
    branches:
      - main

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Fetch Base Branch
      run: |
        git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1

    - name: Get Changed Files
      run: |
        git diff --name-only origin/${{ github.event.pull_request.base.ref }} > changed-files.txt

    - name: Filter Changed Files
      run: |
        grep -E '\.(cpp|hpp|cc|hh|cxx|hxx)$' changed-files.txt > changed-cpp-files.txt || true

    - name: Run Clang-Tidy on Changed Files
      run: |
        if [ -s changed-cpp-files.txt ]; then
          xargs -a changed-cpp-files.txt clang-tidy -- -Iinclude
        else
          echo "No C++ files were changed."
        fi
